version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
