name: Docker Push

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths-ignore:
      - "*.md"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  IMAGE_NAME: kite

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ysicing' }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Build
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task cross-compile
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.action
          push: true
          pull: true
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            KITE_VERSION=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          labels: runnumber=${{ github.run_id }}

      - name: Notify webhook
        continue-on-error: true
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_PASSWORD: ${{ secrets.WEBHOOK_PASSWORD }}
        run: |
          if [ -n "$WEBHOOK_URL" ]; then
            curl -X POST "$WEBHOOK_URL/api/v1/webhooks/events" \
              -H "Content-Type: application/json" \
              -u "kite-webhook:$WEBHOOK_PASSWORD" \
              -d '{
                "action": "restart",
                "resource": "deployments",
                "name": "kite",
                "namespace": "default"
              }'
          else
            echo "WEBHOOK_URL not configured, skipping webhook notification"
          fi
